behaviors:
    DReCon:
        trainer_type: ppo
        hyperparameters:
            num_epoch: 3
            beta: 2e-4
            epsilon: 0.1
            learning_rate: 3e-5
            learning_rate_schedule: linear
            beta_schedule: linear
            epsilon_schedule: linear
            batch_size: 4096 
            buffer_size: 81920
        summary_freq: 10000
        checkpoint_interval: 500000
        keep_checkpoints: 10
        reward_signals:
            extrinsic:
                gamma: 0.995
                strength: 1.0
        network_settings:
            num_layers: 3
            hidden_units: 512
            vis_encode_type: simple
            normalize: true
        max_steps: 1e7
        time_horizon: 1024